# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_simple_version.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_login_simple_version(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 191))
        self.label.setStyleSheet("background-image: url(:/images/images/loginBG.PNG);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/新前缀/pic_show/登录.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 431, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 260, 441, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #ccc; \n"
"padding: 7px 0px;\n"
"border-radius: 8px; /*css3属性IE不支持*/\n"
"padding-left:5px; \n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #66afe9; \n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 330, 441, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 1px solid #ccc; \n"
"padding: 7px 0px;\n"
"border-radius: 8px; /*css3属性IE不支持*/\n"
"padding-left:5px; \n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #66afe9; \n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-10, 180, 811, 351))
        self.label_3.setStyleSheet("background-color: rgba(130, 150, 255,200)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    border-radius:15px;\n"
"    background-color:rgb(0, 170, 255);\n"
"    color:white;\n"
"    border: 1px solid #ccc; \n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"    border-radius:20px;\n"
"    background-color:rgb(0, 170, 255);\n"
"    color:rgb(203, 203, 203);\n"
"    border: 1px solid #ccc; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"    border-radius:15px;\n"
"    background-color:rgb(0, 170, 255);\n"
"    color:white;\n"
"    border: 1px solid #ccc; \n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"    border-radius:20px;\n"
"    background-color:rgb(0, 170, 255);\n"
"    color:rgb(203, 203, 203);\n"
"    border: 1px solid #ccc; \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录"))
        self.label_2.setText(_translate("MainWindow", "CupDisc"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Account"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Register"))
import resMyVersion_rc
